// 由 scripts/build-ui.mjs 生成，**请勿手工编辑**。
// 源在 admin-ui/，改完那边跑 `pnpm ui:build`。产物与源逐字节相同（tests/unit/ui-assets.test.ts 钉死）。
export interface UiAsset {
  readonly body: string;
  readonly type: string;
  readonly etag: string;
}

export const UI_ASSETS: Readonly<Record<string, UiAsset>> = {
  "/admin": { body: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>agnes2api 管理后台</title>\n<!-- 唯一的经典脚本，必须同步、必须在 CSS 之前：防闪白 / 闪错语言。 -->\n<script src=\"/admin/js/boot.js\"></script>\n<link rel=\"stylesheet\" href=\"/admin/css/base.css\">\n</head>\n<body>\n<div class=\"gate\" id=\"gate\">\n  <form class=\"gate-card\" id=\"gate-form\">\n    <h1 data-i18n=\"gate.title\">agnes2api 管理后台</h1>\n    <p class=\"sub\" data-i18n=\"gate.sub\">请输入管理口令（ADMIN_TOKEN）</p>\n    <label for=\"gate-key\" data-i18n=\"gate.label\">管理口令</label>\n    <input id=\"gate-key\" type=\"password\" autocomplete=\"current-password\"\n           data-i18n-ph=\"gate.placeholder\" placeholder=\"ADMIN_TOKEN\">\n    <button type=\"submit\" data-i18n=\"gate.submit\">进入</button>\n    <div class=\"err\" id=\"gate-err\" role=\"alert\"></div>\n  </form>\n</div>\n<div class=\"shell\" id=\"shell\">\n  <h1 data-i18n=\"shell.title\">agnes2api 管理后台</h1>\n  <p data-i18n=\"shell.placeholder\">地基已就绪，功能板块在 P3b 起陆续上线。</p>\n  <p><span data-i18n=\"shell.key\">当前口令</span>：<code id=\"shell-key\"></code></p>\n  <p><span data-i18n=\"shell.version\">网关版本</span>：<code id=\"shell-version\"></code></p>\n</div>\n<script type=\"module\" src=\"/admin/js/app.js\"></script>\n</body>\n</html>\n", type: "text/html; charset=utf-8", etag: "\"e797106a40422251\"" },
  "/admin/css/base.css": { body: "/* 所有颜色一律引用变量，零硬编码色值。主色用 indigo（不是 kiro2api 的 emerald）：\n   同一个运维会同时开着两个结构一模一样的面板，颜色是最快最可靠的区分信号。 */\n:root {\n  --bg: #f7f8fa; --panel: #ffffff; --text: #1c1f26; --muted: #6b7280;\n  --border: #e3e6ec; --primary: #4f46e5; --primary-fg: #ffffff; --danger: #dc2626;\n  --radius: 10px; --gap: 16px;\n}\n:root[data-theme=\"dark\"] {\n  --bg: #14161a; --panel: #1c1f26; --text: #e7e9ee; --muted: #9aa1ad;\n  --border: #2b303a; --primary: #818cf8; --primary-fg: #14161a; --danger: #f87171;\n}\n* { box-sizing: border-box; }\nbody {\n  margin: 0; background: var(--bg); color: var(--text);\n  font: 14px/1.6 system-ui, -apple-system, \"Segoe UI\", \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n}\n.gate { display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: var(--gap); }\n.gate-card {\n  width: 100%; max-width: 380px; padding: 28px; background: var(--panel);\n  border: 1px solid var(--border); border-radius: var(--radius);\n}\n.gate-card h1 { margin: 0 0 4px; font-size: 20px; }\n.gate-card p.sub { margin: 0 0 20px; color: var(--muted); font-size: 13px; }\nlabel { display: block; margin-bottom: 6px; font-size: 13px; color: var(--muted); }\ninput[type=\"password\"] {\n  width: 100%; padding: 10px 12px; margin-bottom: 14px; color: var(--text);\n  background: var(--bg); border: 1px solid var(--border); border-radius: var(--radius);\n}\nbutton {\n  width: 100%; padding: 10px 12px; font: inherit; cursor: pointer;\n  color: var(--primary-fg); background: var(--primary); border: 0; border-radius: var(--radius);\n}\nbutton[disabled] { opacity: .6; cursor: progress; }\n.err { min-height: 20px; margin-top: 10px; color: var(--danger); font-size: 13px; }\n.shell { display: none; padding: var(--gap); }\n.shell.on { display: block; }\n/* 登录成功后隐藏登录闸。用类而不是 style 属性：CSP 的 style-src 'self' 不放行\n   HTML 里的 style=\"…\"，把「隐藏」这件事留在样式表里，将来加板块时不会踩到。 */\n.gate.off { display: none; }\n", type: "text/css; charset=utf-8", etag: "\"63ae572a0390222f\"" },
  "/admin/js/app.js": { body: "/*\n * 登录闸。P3a 只有它——面板本体在 P3b。\n *\n * 两条约束在这里就定死，后面所有板块沿用：\n * ① 口令走 localStorage + `x-admin-key` **请求头**，禁止 Cookie 会话、禁止 `?key=`。\n *    现有鉴权无 Cookie 无 Session ⇒ CSRF 天然不成立；引入 Cookie 就必须同时\n *    加 SameSite=Strict 与 CSRF token，不能只加一半。口令进 URL 会落进浏览器历史、\n *    Referer 与各级访问日志，所以查询参数也一并禁掉。\n * ② 一切来自接口的内容一律 textContent，不用 innerHTML。\n */\nimport { maskKey } from \"./pure/mask.mjs\";\n\nconst KEY_STORE = \"agnes2api_admin_key\";\nconst gate = document.getElementById(\"gate\");\nconst shell = document.getElementById(\"shell\");\nconst form = document.getElementById(\"gate-form\");\nconst input = document.getElementById(\"gate-key\");\nconst err = document.getElementById(\"gate-err\");\nconst who = document.getElementById(\"shell-key\");\nconst ver = document.getElementById(\"shell-version\");\n\n/** localStorage 在隐私模式下会抛，读写一律包起来——它不该能挡住登录。 */\nfunction store(op, value) {\n  try {\n    if (op === \"get\") return localStorage.getItem(KEY_STORE);\n    if (op === \"set\") localStorage.setItem(KEY_STORE, value);\n    if (op === \"del\") localStorage.removeItem(KEY_STORE);\n  } catch (e) {\n    // 存不下就存不下：本次会话照常可用，只是刷新后要重新输入。\n  }\n  return null;\n}\n\nasync function probe(key) {\n  const res = await fetch(\"/admin/api/session\", { headers: { \"x-admin-key\": key } });\n  if (res.status === 401) return { ok: false, reason: \"unauthorized\" };\n  // 403 **不当会话失效**：将来某个操作被拒绝时把人踢出后台并告知「密钥无效」，\n  // 是 kiro2api 踩过的坑。这里只有 401 才算登录失败。\n  if (!res.ok) return { ok: false, reason: \"http_\" + res.status };\n  return { ok: true, body: await res.json() };\n}\n\nfunction enter(key, body) {\n  gate.classList.add(\"off\");\n  shell.classList.add(\"on\");\n  // 掩码后再显示：明文口令留在页面上，一次截图就泄漏了。\n  who.textContent = maskKey(key);\n  ver.textContent = String(body && body.version ? body.version : \"—\");\n}\n\nform.addEventListener(\"submit\", async (e) => {\n  e.preventDefault();\n  const key = input.value.trim();\n  err.textContent = \"\";\n  if (!key) { err.textContent = \"请输入管理口令\"; return; }\n  const submit = form.querySelector(\"button\");\n  submit.disabled = true;\n  try {\n    const r = await probe(key);\n    if (!r.ok) {\n      // 失败**绝不**写入 localStorage，也不显示「已登录」。\n      err.textContent = r.reason === \"unauthorized\" ? \"口令无效\" : \"接口异常：\" + r.reason;\n      return;\n    }\n    store(\"set\", key);\n    enter(key, r.body);\n  } catch (e2) {\n    err.textContent = \"网络错误，请稍后重试\";\n  } finally {\n    submit.disabled = false;\n  }\n});\n\n// 已经存过口令就直接验一次；**验不过要清掉**，否则用户会卡在一个永远进不去的页面。\n// 只有 401 才清：接口 500 或断网时清掉等于让一次运维事故顺手把人锁在外面。\nconst saved = store(\"get\");\nif (saved) {\n  probe(saved).then((r) => {\n    if (r.ok) enter(saved, r.body);\n    else if (r.reason === \"unauthorized\") store(\"del\");\n  }).catch(() => {});\n}\n", type: "text/javascript; charset=utf-8", etag: "\"7bef3edfda787b20\"" },
  "/admin/js/boot.js": { body: "/*\n * 全站唯一的经典脚本：<head> 里同步执行、**不许加 defer / type=\"module\"**。\n *\n * 模块脚本天然 defer，会在 body 绘制之后才跑，于是每次刷新都能看见一次亮色闪白\n *（或一次错误的语言）。这条约束写在这里，改动前先读它。\n *\n * 它也是全站唯一允许在 CSS 之前加载的脚本——主题属性必须在样式表生效前落到\n * <html> 上，否则 :root[data-theme=\"dark\"] 那一整组覆盖会晚一帧。\n */\n(function () {\n  try {\n    var theme = localStorage.getItem(\"agnes2api_theme\");\n    if (theme === \"dark\") document.documentElement.setAttribute(\"data-theme\", \"dark\");\n    // light 时**移除属性**而不是设成 \"light\"：CSS 里 :root 是亮色全量 token，\n    // [data-theme=\"dark\"] 整体覆盖，多一个 light 值只会多一条永远匹配不上的规则。\n    var lang = localStorage.getItem(\"agnes2api_lang\") || \"zh-CN\";\n    document.documentElement.setAttribute(\"data-lang\", lang);\n    document.documentElement.lang = lang;\n  } catch (e) {\n    // localStorage 被禁用（隐私模式 / 三方 cookie 拦截）时什么都不做，走默认外观。\n    // 这里**不能抛**：它是同步脚本，抛出去会让后面的样式表和模块脚本一起停摆。\n  }\n})();\n", type: "text/javascript; charset=utf-8", etag: "\"8a498ad988cce75a\"" },
  "/admin/js/pure/mask.mjs": { body: "/**\n * 上游 key 的掩码。\n *\n * `KeyPoolRepo.all()` 返回的记录含完整明文 key，直接吐给面板等于把整池上游 key\n * 交出去，所以掩码是硬规则，不是显示偏好。\n *\n * **这个目录（js/pure）下的文件受三条硬规则约束**，由 scripts/build-ui.mjs 与\n * tests/unit/ui-assets.test.ts 各守一道，规则全文见 admin-ui/README.md。\n * 其中一条禁止触碰浏览器全局，而校验是**纯文本匹配、不解析注释**——所以那几个\n * 全局的名字连注释里都不许写出来，本文件因此只在 README 里展开说明。\n */\nexport function maskKey(key) {\n  // 阈值 10：再短就不值得掩码了（前 5 + 后 4 会把几乎整串露出来），一律整串隐去。\n  // **绝不返回原值**：返回原值的「掩码」比没有掩码更糟，调用方会以为它安全了。\n  if (typeof key !== \"string\" || key.length <= 10) return \"…\";\n  return `${key.slice(0, 5)}…${key.slice(-4)}`;\n}\n", type: "text/javascript; charset=utf-8", etag: "\"00ab474c062a7ade\"" },
};

export const UI_BUILD_HASH = "37f38fc8db89d50d";
